name: flix_id
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  flutter_riverpod: ^2.4.9
  path: ^1.8.3
  dio: ^5.4.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/
